SELECT 
    IT.PRODUTO AS COD_PRODUTO,
    IT.NOME AS DESCRICAO_PRODUTO,
    PROD.UNID AS UNIDADE,
    COUNT(DISTINCT IT.PEDIDO) AS QTD_PEDIDOS_DISTINTOS,
    SUM(IT.QTDE) AS QTD_TOTAL_VENDIDA,
    SUM(IT.VTOTAL) AS RECEITA_TOTAL,
    AVG(IT.VUNIT) AS PRECO_MEDIO,
    SUM(IT.VTOTAL_LIQ) AS RECEITA_LIQUIDA,
    AVG(IT.PERC_MARG_CONTRIBUICAO) AS MARGEM_MEDIA_PERC,
    SUM(IT.VR_MARG_CONTRIBUICAO) AS MARGEM_TOTAL_RS,
    SUM(IT.PESO_BRUTO * IT.QTDE) AS PESO_TOTAL_VENDIDO_KG
FROM 
    ARQES09 IT
INNER JOIN 
    ARQES07 PED 
        ON PED.PEDIDO = IT.PEDIDO
LEFT JOIN
    ARQES01 PROD
        ON PROD.CODIGO = IT.PRODUTO
       AND PROD.COD_COR = IT.COD_COR
       AND PROD.COD_TAMANHO = IT.COD_TAMANHO
WHERE 
    PED.SITUACAO <> 'C'
    AND PED.DATA >= CURRENT_DATE - 90
GROUP BY 
    IT.PRODUTO, 
    IT.NOME,
    PROD.UNID
ORDER BY 
    QTD_TOTAL_VENDIDA DESC
LIMIT 50;
